# Generated by Django 4.2.17 on 2025-05-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='service',
            field=models.CharField(choices=[('controller', 'Controller'), ('worker', 'Worker'), ('database', 'Database'), ('api_gateway', 'API Gateway'), ('scheduler', 'Scheduler')], max_length=32),
        ),
    ]
